"""add resume upload limits

Revision ID: 843eb31f0515
Revises: 9aa575bd56b9
Create Date: 2026-09-17 16:22:41.313467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843eb31f0515'
down_revision: Union[str, Sequence[str], None] = '9aa575bd56b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_upload_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier_hash', sa.String(length=64), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('upload_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_hash', 'upload_date', name='uq_resume_upload_identifier_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_upload_limits')
    # ### end Alembic commands ###
