"""add user authentication

Revision ID: ef97151dfe2a
Revises: 843eb31f0515
Create Date: 2026-09-17 16:31:52.753062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef97151dfe2a'
down_revision: Union[str, Sequence[str], None] = '843eb31f0515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('resume_upload_limits', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_resume_upload_identifier_date'), 'resume_upload_limits', type_='unique')
    op.create_index(op.f('ix_resume_upload_limits_user_id'), 'resume_upload_limits', ['user_id'], unique=False)
    op.create_unique_constraint('uq_resume_upload_user_date', 'resume_upload_limits', ['user_id', 'upload_date'])
    op.create_foreign_key('fk_resume_upload_limits_user_id_users', 'resume_upload_limits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resume_upload_limits', 'identifier_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_upload_limits', sa.Column('identifier_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint('fk_resume_upload_limits_user_id_users', 'resume_upload_limits', type_='foreignkey')
    op.drop_constraint('uq_resume_upload_user_date', 'resume_upload_limits', type_='unique')
    op.drop_index(op.f('ix_resume_upload_limits_user_id'), table_name='resume_upload_limits')
    op.create_unique_constraint(op.f('uq_resume_upload_identifier_date'), 'resume_upload_limits', ['identifier_hash', 'upload_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('resume_upload_limits', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
